name: Book Court Script

on:
  schedule:
    - cron: '20 7 * * *'  # Runs at 07:20 AM UTC every day/ PST post 12AM
    #- cron: '0 * * * *' # every minute for debugging

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set execute permission
        run: chmod +x tools/book-court.sh
      
      - name: Run shell script
        run: ./tools/book-court.sh
